# Generated by Django 3.1.4 on 2021-01-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201231_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False, 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
