# Generated by Django 3.1.4 on 2021-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='test',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
