# Generated by Django 3.1.4 on 2021-01-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categories_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='test',
        ),
    ]
