image: "python:3.7"

before_script:
  - python --version
  - pip install -r ./core/api/requirements.txt

stages:
  - FlakeControl
  - TestApi
  - endtest

lint:
  stage: FlakeControl
  script:
    -  flake8 ./core/api

testAPI:
  stage: TestApi
  script:
  - pytest ./core/api/

endtest:
  stage: endtest
  script:
    -  python --version
