default:
  image:  python:3.7
  only:
    - production
  tags:
    - test
  script:
    - sudo docker-compose build web
    - sudo docker-compose up -d web
# image: "python:3.7"
# testrtml
# before_script:
#   - python --version
#   - pip install -r ./core/api/requirements.txt

# stages:
#   - FlakeControl
#   - TestApi
#   - endtest

# lint:
#   stage: FlakeControl
#   script:
#     -  flake8 ./core/api

# testAPI:
#   stage: TestApi
#   script:
#   - pytest ./core/api/

# PRODUCTION:
#   stage: endtest
#   script:
#     -  python --version
