image: "python:3.7"

before_script:
  - python --version
  - pip install -r ./core/api/requirements.txt

stages:
  - pretest
  - Test
  -endtest

pretest:
  stage:
  script:
    -  python --version

pytest:
  stage: Test
  script:
  - pytest

endtest:
  stage:
  script:
    -  python --version