default:
  image:  python:3.7
  only:
    - production
  tags:
    - test
  script:
    - sudo docker stop $(sudo  docker  ps  -a  -q)
    - sudo docker build web
    - sudo docker run -d -p web
# image: "python:3.7"
# testrt
# before_script:
#   - python --version
#   - pip install -r ./core/api/requirements.txt

# stages:
#   - FlakeControl
#   - TestApi
#   - endtest

# lint:
#   stage: FlakeControl
#   script:
#     -  flake8 ./core/api

# testAPI:
#   stage: TestApi
#   script:
#   - pytest ./core/api/

# PRODUCTION:
#   stage: endtest
#   script:
#     -  python --version
