image: "python:3.7"

before_script:
  - python --version
  - pip install -r ./core/api/requirements.txt

stages:
  - FlakeControl
  - Test
  - endtest

pretest:
  stage: FlakeControl
  script:
    -  flake8 ./core/api

pytest:
  stage: Test
  script:
  - pytest

endtest:
  stage: endtest
  script:
    -  python --version
