
version: "3"
   
services:
  api:
    build: ./core/api 
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload --app-dir="./core/api"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'products_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'will'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Djibouti1788!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'djibouti'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./dump_db:/docker-entrypoint-initdb.d

    
  web:
    build: ./core/admin
    command: python /app/manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    depends_on:
      - db
volumes:
  my-db:
